services:
  - type: web
    name: trade-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd trade_opportunities_api && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GOOGLE_API_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.7
